# Generated by Django 4.1.1 on 2022-09-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contents2',
            field=models.TextField(default=''),
        ),
    ]
