# Generated by Django 4.1.1 on 2022-09-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0003_post_mainphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date published'),
        ),
    ]
