# Generated by Django 4.1.1 on 2022-11-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0004_alter_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_date_k',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='wishnote',
            field=models.CharField(default='', max_length=200),
        ),
    ]
