# Generated by Django 4.1.1 on 2022-11-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0005_post_pub_date_k_post_wishnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='color_k',
            field=models.CharField(default='black', max_length=200),
        ),
    ]
