# Generated by Django 4.1.1 on 2022-11-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotto', '0006_post_color_k'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='color_k',
            field=models.CharField(default='lucky.png', max_length=200),
        ),
    ]
